-- SHOW DATABASES;
-- DROP DATABASE BLOCKCHAIN
-- CREATE DATABASE BLOCKCHAIN 
-- IF NOT EXISTS BLOCKCHAIN;
USE `BLOCKCHAIN`;

DROP TABLE IF EXISTS `USER`;

-- CREATE TABLE `USERS` (
--     `USER_ID` INT AUTO_INCREMENT,
--     `USER_NAME` VARCHAR(255) NOT NULL,
--     `BALANCE` INT DEFAULT 10000,
--     `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (`USER_ID`)
-- );

-- INSERT INTO `USERS` (`USER_NAME`) VALUES('ABDULLAH');
-- INSERT INTO `USERS` (`USER_NAME`) VALUES('ALI');
-- INSERT INTO `USERS` (`USER_NAME`) VALUES('AHMED');

SELECT * FROM `USERS`;

